### ISSUE TITLE
Incorrect URL when using private haste server

### ISSUE THREAD

**Issue by knulped** [ajryan/WinHaste#3]
I run WinHaste.exe http://deaddrop.in C:\Users\myuser\Desktop\pingtest.txt
I get output:
Haste URL: http://hastebin.com/zixohogemu <copied to clipboard>

If I paste the url into my browser and change to http://deaddrop.in/zixohogemu , I get the correct upload.

**Comment by ajryan** [comment]
Thanks for reporting this. It's fixed in cfa3ced2dd3e1a32f433cc4ad3e454f82d29ec8a
