### ISSUE TITLE
File is used by another process

### ISSUE THREAD

**Issue by tekmans** [ajryan/WinHaste#6]
If already used file could be handle, it could be useful

> .\winhaste.exe https://mypaste.net 'C:\Program Files\MyProg\my.log'
> 
> Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Program Files\MyProg\my.log' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
>    at System.IO.File.ReadAllText(String path)
>    at WinHaste.Program.Main(String[] args)

Thx

**Comment by aidanjryan** [comment]
Winhaste only opens the file for reading. If it cannot be opened, it means whatever program is writing the file has not opened it in a way that allows shared reads.

**Comment by ajryan** [comment]
Winhaste only opens the file for reading. If it cannot be opened, it means whatever program is writing the file has not opened it in a way that allows shared reads.

**Comment by tekmans** [comment]
Hi 
I'm understand your anwser, but if i do

type c:\path\myfile.log
i can view content

only winhaste http://myhaster.server c:\path\myfile.log give me the previous message in my original post

As you might understood is a log file, i could be nice to do not stop the process to grab the log

**Comment by ajryan** [comment]
Thanks for following up. Actually I looked a bit closer and `File.ReadAllText` actually does not allow concurrent writing. So I should be able to drop down to the stream level and work with files that are open for logging. I'll take a look at this.

**Comment by tekmans** [comment]
thx because your tools is really helpfull to remotly grab log file

**Comment by ajryan** [comment]
Please try the latest binary - it should be able to read open files.

**Comment by tekmans** [comment]
Hi please have a look

![image](https://user-images.githubusercontent.com/1766087/41105451-1429a6fe-6a6e-11e8-9651-4f7bca8dffce.png)


![image](https://user-images.githubusercontent.com/1766087/41105319-bbe4820c-6a6d-11e8-8b9d-ca0ee1227c17.png)

![image](https://user-images.githubusercontent.com/1766087/41105899-0f7eb080-6a6f-11e8-8b3a-05fb210011d8.png)

The file https://files.fm/u/arf4ace5

**Comment by tekmans** [comment]
Could it be the file size ?
![image](https://user-images.githubusercontent.com/1766087/41109177-a4081dc0-6a76-11e8-8b0e-78f01ea7342b.png)

**Comment by ajryan** [comment]
That's a good possibility, how large is the file?

**Comment by tekmans** [comment]
Because first of all i have purged all specifics characters, and it still gave me the same error.. then i cut the file in piece.. as you can see my previous screenshoots +/- 300Ko was OK and +/- 500Ko KO
It's really small file.. but

**Comment by ajryan** [comment]
I'm pretty sure 400,000 characters is the limit, see here:
https://github.com/seejohnrun/haste-server/issues/35

**Comment by ajryan** [comment]
Also, I see from the source it includes error descriptions in the response.
I should be able to update the code to write out the error message to help
troubleshoot.

**Comment by tekmans** [comment]
Hi goods news,
I have increased in ./config.js:8:  "maxLength": 400000 upto 4 000 000 lines.
This log file used by another process had been upload successfully.
THx
