### ISSUE TITLE
Comodo Auto-Sandbox prevents link from being copied to clipboard.

### ISSUE THREAD

**Issue by AetherCollective** [ajryan/WinHaste#7]
Comodo Internet Security Free (and it's paid equivalents) make use of a technology called Auto-Sandbox. This automatically sandboxes any processes that aren't trusted. Comodo keeps a list of Trusted Vendors and hashes. Anything not on that list get's auto-sandboxed. Normally it does a good job about keeping most popular software on the list, but yours isn't so well known. 

This only effects copy to clipboard functionality. The core functionality works even while auto-sandboxed.

There are several fixes/workarounds:
1. Create an Auto-Sandbox exception for WinHaste.exe
2. Sign WinHaste.exe. Then create an Auto-Sandbox exception for the Vendor.
3. Contact Comodo and ask for recommendations. https://support.comodo.com/

For unmanaged installations:
https://help.comodo.com/topic-72-1-766-9170-Auto-Containment-Rules.html

For managed installations: (Yes, same service, different skins. idk why)
Comodo One: https://help.comodo.com/topic-399-1-786-10102-Manage-File-Trust-Ratings-on-Windows-Devices.html
ITarian: https://community.itarian.com/help/topic-399-1-786-10102-Manage-File-Trust-Ratings-on-Windows-Devices.html

More Resources: 
Comodo Valkyrie: https://valkyrie.comodo.com/get_info?sha1=1A30B02ED97B88620AF14F79B78FB46BFC5FFBDB

Ticket for commit 3f0e6a8

**Comment by aidanjryan** [comment]
I will definitely not be doing anything about this.

**Comment by ajryan** [comment]
Can't see how this is anyone's problem except whoever is dumb enough to use this comodo thing.

**Comment by ajryan** [comment]
did you create this issue as an FYI for other users? or are you expecting me to do something?

**Comment by AetherCollective** [comment]
Both. Nice to meet you too btw. You have beef with comodo?

**Comment by ajryan** [comment]
This is 100% Not My Problem™

"Hey cabinet manufacturer, I bought a child lock and stuck it on your drawer but it makes it hard for me to get stuff out. Please fix my mistake for me."

**Comment by AetherCollective** [comment]
Alright, have a good day. It was my mistake to report this issue.
